# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0b17d954003d73ca3a65da5e24f2bcf688dd8d399f5a59c4c5d8a64d69d785ce1e34f3bd6788d8a27fac806c5fe57896e7e9649caf1a4b85d3a63fdd810e44

test:
  secret_key_base: 1783e435d023b29bf32e10333071a282258eb5caeb7d22de5644c0ff74d9b04343108ecdfb7e1aed9027f2994474c4625f065fdf4fbd99fb87aa5cabad63dc5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
